package model;

// default package
// Generated 2017/9/21 下午 04:21:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockDailyRecord generated by hbm2java
 */
@Entity
@Table(name = "STOCK_DAILY_RECORD", catalog = "STOCK")
public class StockDailyRecord implements java.io.Serializable {

	private Integer dailyRecordId;
	private Stock stock;
	private float priceOpen;
	private float priceClose;
	private float priceChange;
	private int volume;
	private Date date;
	private int stockId;

	public StockDailyRecord() {
	}

	public StockDailyRecord(float priceOpen, float priceClose, float priceChange, int volume, Date date, int stockId) {
		this.priceOpen = priceOpen;
		this.priceClose = priceClose;
		this.priceChange = priceChange;
		this.volume = volume;
		this.date = date;
		this.stockId = stockId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DAILY_RECORD_ID", unique = true, nullable = false)
	public Integer getDailyRecordId() {
		return this.dailyRecordId;
	}

	public void setDailyRecordId(Integer dailyRecordId) {
		this.dailyRecordId = dailyRecordId;
	}

	@Column(name = "PRICE_OPEN", nullable = false, precision = 12, scale = 0)
	public float getPriceOpen() {
		return this.priceOpen;
	}

	public void setPriceOpen(float priceOpen) {
		this.priceOpen = priceOpen;
	}

	@Column(name = "PRICE_CLOSE", nullable = false, precision = 12, scale = 0)
	public float getPriceClose() {
		return this.priceClose;
	}

	public void setPriceClose(float priceClose) {
		this.priceClose = priceClose;
	}

	@Column(name = "PRICE_CHANGE", nullable = false, precision = 12, scale = 0)
	public float getPriceChange() {
		return this.priceChange;
	}

	public void setPriceChange(float priceChange) {
		this.priceChange = priceChange;
	}

	@Column(name = "VOLUME", nullable = false)
	public int getVolume() {
		return this.volume;
	}

	public void setVolume(int volume) {
		this.volume = volume;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	/*@Column(name = "STOCK_ID", nullable = false)
	public int getStockId() {
		return this.stockId;
	}

	public void setStockId(int stockId) {
		this.stockId = stockId;
	}
*/
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name ="STOCK_ID",nullable = false)
	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Override
	public String toString() {
		return "StockDailyRecord [dailyRecordId=" + dailyRecordId + ", stock=" + stock + ", priceOpen=" + priceOpen
				+ ", priceClose=" + priceClose + ", priceChange=" + priceChange + ", volume=" + volume + ", date="
				+ date + ", stockId=" + stockId + "]";
	}

	
	
	
}
